sudo: false

language: node_js

node_js:
- 'iojs'

git:
  depth: 1

env:
  global:
  - BROWSERS=SL_Chrome,SL_Firefox,SL_IE_9,SL_IE_10,SL_IE_11,SL_Safari,SL_Opera
  - SAUCE_USERNAME=javiercejudo
  - secure: PP7iX1E/QBQJiUSSbFzZMWav4d3HXxe622KyOo97T36EHzz7Tm0ofZKRquAJVdmGTHJVE5WOII/dQ4wp9WvI1HSe6Mqn2oJfl5Bu86zk5KPooON4Jduz4V/bqtzwhCTDmkJ8QEGBAXSPQ2al9linVejXhWto3o2h8Iu5L5ZHMQY=
  - secure: NP6lDYgTooItAuuJGSGh8DNmBPAu0JaGCi5MBE7976AvzybBL3sJBClZ8oYDfVlSxAMYcdYaUKLz3OpCLmvjVr8/ujZjtDoYwAGw92rPdklj0B5y2icbO8ulC+V1rNFAh1Al79zB/X9lLPdMBSEN3a5/PgNpbFnw4NcEfHodPBc=
  - secure: GNdL+ez0b6MuFd8jgnjxx0VqBd9ktJH11365P9yAA+Dq/lmiCd4hFZHkVwEzSdwibL8sixWWz/6Ox732S5LyNVI2//jjjHbppYLTtNEpMPlIlR9k27EGIFIifmO8o0wqkNpgdJzxkl8OOYebQR6roo/n4TsWTDIO9C6pD2Jon+0=
matrix:
  fast_finish: true

addons:
  sauce_connect: true

before_install:
- git fetch --unshallow
# - ./scripts/setup-timezone.sh
- npm install -g npm@latest

after_success:
- gulp coveralls

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: bNRd9ba3QLhBfSbxMBb1chOZ0EogBbiGTjDP+R44BdwXkZSlu/2w5Jg4w/VGzG82IfZLYHDjCFCMJflQQlmCSE0/IStq3P+y/yu/4DIVY5GNLfTE6EUxF66YMsv0HorG8OMg6KR/e2USbCI1bZpT/SwJ0XOYD1LCCkvreJr8U+A=
  strategy: git
  app:
    master: javiercejudo
    staging: javiercejudo-staging
  on:
    repo: javiercejudo/javiercejudo.com

after_deploy:
- ./scripts/publish-wraith.sh

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/afebf4197a02d9ac890f
    on_success: always
    on_failure: always
