language: node_js

node_js:
- 0.1

git:
  depth: 1

before_install:
- git fetch --unshallow

after_success:
- gulp coveralls

env:
  matrix:
  - BROWSER=SL_Chrome
  - BROWSER=SL_Firefox
  - BROWSER=SL_Safari
  - BROWSER=SL_IE_9
  - BROWSER=SL_IE_10
  - BROWSER=SL_IE_11
  - BROWSER=SL_Opera
  - BROWSER=SL_Android
  - BROWSER=SL_iOS
  global:
  - secure: NP6lDYgTooItAuuJGSGh8DNmBPAu0JaGCi5MBE7976AvzybBL3sJBClZ8oYDfVlSxAMYcdYaUKLz3OpCLmvjVr8/ujZjtDoYwAGw92rPdklj0B5y2icbO8ulC+V1rNFAh1Al79zB/X9lLPdMBSEN3a5/PgNpbFnw4NcEfHodPBc=
  - secure: GNdL+ez0b6MuFd8jgnjxx0VqBd9ktJH11365P9yAA+Dq/lmiCd4hFZHkVwEzSdwibL8sixWWz/6Ox732S5LyNVI2//jjjHbppYLTtNEpMPlIlR9k27EGIFIifmO8o0wqkNpgdJzxkl8OOYebQR6roo/n4TsWTDIO9C6pD2Jon+0=

matrix:
  fast_finish: true
  allow_failures:
  - env: BROWSER=SL_Firefox
  - env: BROWSER=SL_Safari
  - env: BROWSER=SL_IE_9
  - env: BROWSER=SL_IE_10
  - env: BROWSER=SL_IE_11
  - env: BROWSER=SL_Opera
  - env: BROWSER=SL_Android
  - env: BROWSER=SL_iOS

addons:
  sauce_connect:
    username: javiercejudo
    access_key:
      secure: ONViR0Xn0yRJ2JDnQjPO60MlOkypwd3fjFzuJ+KsMqMrWwJr2owYb03l3vJgRetdWRkwOF03KMx0M1+oVTgn1FA4cMvuoahoKq3rf1uqMM/rmfn1sm6hpTE/hgOZzhjZrW/kecKZQCqAMIuL3jrZqcui3LwM/9mlnGlh1nLc/jc=

before_deploy:
- gulp publish-build

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: bNRd9ba3QLhBfSbxMBb1chOZ0EogBbiGTjDP+R44BdwXkZSlu/2w5Jg4w/VGzG82IfZLYHDjCFCMJflQQlmCSE0/IStq3P+y/yu/4DIVY5GNLfTE6EUxF66YMsv0HorG8OMg6KR/e2USbCI1bZpT/SwJ0XOYD1LCCkvreJr8U+A=
  strategy: git
  app:
    master: javiercejudo
    staging: javiercejudo-staging
  on:
    repo: javiercejudo/javiercejudo.com
    condition: $BROWSER = SL_Chrome

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/afebf4197a02d9ac890f
    on_success: always
    on_failure: always
