language: node_js
node_js:
  - 0.10
before_script:
  - bower install
  - bower install
deploy:
   provider: heroku
   api_key:
     secure: bNRd9ba3QLhBfSbxMBb1chOZ0EogBbiGTjDP+R44BdwXkZSlu/2w5Jg4w/VGzG82IfZLYHDjCFCMJflQQlmCSE0/IStq3P+y/yu/4DIVY5GNLfTE6EUxF66YMsv0HorG8OMg6KR/e2USbCI1bZpT/SwJ0XOYD1LCCkvreJr8U+A=
   strategy: git
   app: javiercejudo
   on:
     repo: javiercejudo/javiercejudo.com
   run:
     - "ls -la www/"
     - "cp www/config.template.php www/config.php"
     - "cp www/.htaccess.template www/.htaccess"
     - "ls -la www/"
