#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "./slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "nojs.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots_nojs'

# Add only 2 domains, key will act as a label
domains:
  dev: "http://javiercejudo.dev"
  staging: "http://staging.javiercejudo.com"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  - 768
  - 1024
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
  1_home: /
  2_cv: /#!/cv/english
  3_game: /#!/game/10
  4_404: /#!/404

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

