# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

# (required) The directory that your screenshots will be stored in
directory: 'shots'

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/wait--phantom.js'

# (required) The domains to take screenshots of.
domains:
  live: "https://www.javiercejudo.com"
  staging: "http://staging.javiercejudo.com"

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 360
  - 768
  - 1280

# (required) The paths to capture. All paths should exist for both of the domains specified above.
paths:
  home: /#!/
  cv: /#!/cv/english
  game: /#!/game/10
  error: /#!/404

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '5%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 0.05
